title:  Readiness Quiz - Introduction to Programming with Python  
description: This quiz tests your knowledge of fundamentals of Python programming, including using variables, for loops, lists, conditional statements, functions and importing external libraries.
markdown: kramdown 
kramdown: 
  input: GFM 